<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sass</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*([-%#\:\.\w\=].*)\s$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$</string>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>Better Sass</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(\s*)(//|/\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.comment.sass</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1  )</string>
			<key>name</key>
			<string>comment.block.sass</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.sass</string>
				</dict>
			</array>
		</dict>
    <dict>
      <key>match</key>
      <string>".*(?&lt;!\\)"</string>
      <key>name</key>
      <string>constant.string.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>^\s*(@\S+|\+|=)</string>
      <key>name</key>
      <string>keyword.control.directive.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>!default</string>
      <key>name</key>
      <string>keyword.other.default.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\$[\w-]+(:)</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.separator.declaration.sass</string>
        </dict>
      </dict>
      <key>name</key>
      <string>variable.declaration.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\$[\w-]+</string>
      <key>name</key>
      <string>variable.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(#)[0-9a-fA-F]+\b</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>keyword.other.unit.sass</string>
        </dict>
      </dict>
      <key>name</key>
      <string>constant.other.color.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(?:(?&lt;=\s)-)?\b\d+(\.\d+)?(%|[a-z]*)</string>
      <key>name</key>
      <string>constant.numeric.sass</string>
      <key>captures</key>
      <dict>
        <key>2</key>
        <dict>
          <key>name</key>
          <string>keyword.other.unit.sass</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>match</key>
      <string>(?&lt;=\s|^)\w+(?=\()</string>
      <key>name</key>
      <string>keyword.other.function.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>^\s*[a-zA-Z-]+:</string>
      <key>name</key>
      <string>keyword.other.parameter.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>&amp;|&gt;|\+|\(|\)</string>
      <key>name</key>
      <string>keyword.operator.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(\.)[\w-]+</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.tag.sass</string>
        </dict>
      </dict>
      <key>name</key>
      <string>entity.name.tag.class</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(\#)[\w-]+</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.tag.sass</string>
        </dict>
      </dict>
      <key>name</key>
      <string>entity.name.tag.id</string>
    </dict>
    <dict>
      <key>match</key>
      <string>(?&lt;!\s)(\:)[\w-]+</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>punctuation.definition.tag.sass</string>
        </dict>
      </dict>
      <key>name</key>
      <string>entity.other.pseudo-class.sass</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?:a|abbr|acronym|address|applet|area|b|base|basefont|bdo|big|blockquote|body|br|button|caption|center|cite|code|col|colgroup|dd|del|dfn|dir|div|dl|dt|em|fieldset|font|form|frame|frameset|h1|h2|h3|h4|h5|h6|head|hr|html|i|iframe|img|input|ins|isindex|kbd|label|legend|li|link|map|menu|meta|noframes|noscript|object|ol|optgroup|option|p|param|pre|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|ul|var)\b</string>
      <key>name</key>
      <string>entity.name.tag.sass</string>
    </dict>
  </array>
	<key>scopeName</key>
	<string>text.sass</string>
	<key>uuid</key>
	<string>3D727049-DD05-45DF-92A5-D50EA36FD036</string>
</dict>
</plist>
